'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace ManhattanBar3DChart.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As ManhattanBar3DChart.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New ManhattanBar3DChart.Properties.Settings())), ManhattanBar3DChart.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return ManhattanBar3DChart.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
